### ISSUE TITLE
comparing to similar repos

### ISSUE THREAD

**Issue by eps696** [siyuhuang/PoseStylizer#1]
hello, 
did you compare your results to [Global-Flow-Local-Attention](https://github.com/RenYurui/Global-Flow-Local-Attention) or [CoCosNet](https://github.com/microsoft/CoCosNet), dealing with the same task and datasets?

**Comment by siyuhuang** [comment]
Not yet. 

Our paper was submitted (to IJCAI'20) before the release of CVPR'20 papers. You could compare the results easily by running the codes.
