### ISSUE TITLE
bad test result 

### ISSUE THREAD

**Issue by linyh1998** [siyuhuang/PoseStylizer#10]
Hi.Impressive work product.
I test the dataset using pretrained model and I got bad result.Can you tell me what went wrong?

![1](https://user-images.githubusercontent.com/63727075/105170139-7b122080-5b57-11eb-80db-bbe98753ffdf.png)

**Comment by Ha0Tang** [comment]
@linyh1998 have you solved this?

**Comment by Ha0Tang** [comment]
I ran into the same problem.

**Comment by siyuhuang** [comment]
@linyh1998 @Ha0Tang

Please check the checkpoint loading process. Please see issues [2](https://github.com/siyuhuang/PoseStylizer/issues/2) and [7](https://github.com/siyuhuang/PoseStylizer/issues/7) for suggestions.

**Comment by Ha0Tang** [comment]
Thanks, I can produce the results on the market dataset, but not on the deepfashion dataset.

I have read these two questions and determined that the same environment is used on both data sets.

**Comment by siyuhuang** [comment]
> Thanks, I can produce the results on the market dataset, but not on the deepfashion dataset.
> 
> I have read these two questions and determined that the same environment is used on both data sets.

I am not sure what is wrong with your case. You may provide more details.

**Comment by Ha0Tang** [comment]
This is the command line for the market dataset:

python -u test.py --dataroot ./datasets/market_data/ --phase test --norm batch --batchSize 1 --resize_or_crop no --BP_input_nc 18 --no_flip --how_many 100000 --pairLst ./datasets/market_data/market-pairs-test.csv --display_id 0 --which_epoch latest --gpu_ids 0,1 --G_n_downsampling 4 --ngf 64 --model PoseStyleNet --results_dir ./results --name market_APS --which_model_netG APS --dataset_mode keypoint

This is the command line for the deepfashion dataset:

python -u test.py --dataroot ./datasets/fashion_data/ --dataset fashion --phase test --norm instance --batchSize 1 --ngf 64 --resize_or_crop no --gpu_ids 0,1 --BP_input_nc 18 --no_flip --pairLst ./datasets/fashion_data/fasion-resize-pairs-test.csv --display_id 0 --which_epoch latest --how_many 100000 --G_n_downsampling 5 --results_dir ./results --model PoseStyleNet --name fashion_APS --which_model_netG APS --dataset_mode keypoint

What other details would you like me to provide? Please let me know, thanks.

**Comment by siyuhuang** [comment]
> This is the command line for the market dataset:
> 
> python -u test.py --dataroot ./datasets/market_data/ --phase test --norm batch --batchSize 1 --resize_or_crop no --BP_input_nc 18 --no_flip --how_many 100000 --pairLst ./datasets/market_data/market-pairs-test.csv --display_id 0 --which_epoch latest --gpu_ids 0,1 --G_n_downsampling 4 --ngf 64 --model PoseStyleNet --results_dir ./results --name market_APS --which_model_netG APS --dataset_mode keypoint
> 
> This is the command line for the deepfashion dataset:
> 
> python -u test.py --dataroot ./datasets/fashion_data/ --dataset fashion --phase test --norm instance --batchSize 1 --ngf 64 --resize_or_crop no --gpu_ids 0,1 --BP_input_nc 18 --no_flip --pairLst ./datasets/fashion_data/fasion-resize-pairs-test.csv --display_id 0 --which_epoch latest --how_many 100000 --G_n_downsampling 5 --results_dir ./results --model PoseStyleNet --name fashion_APS --which_model_netG APS --dataset_mode keypoint
> 
> What other details would you like me to provide? Please let me know, thanks.

They are the default `.sh` settings. I suspect the problem is not loading the checkpoint correctly. Please kindly try to track and validate the loading process.

**Comment by Ha0Tang** [comment]
![image](https://user-images.githubusercontent.com/23024709/108885952-b301fd00-7608-11eb-94d0-f6c7d2c3ffaf.png)

@siyuhuang Does this mean that the pre-trained checkpoints are loaded correctly? Thanks.

**Comment by Ha0Tang** [comment]
@siyuhuang I cannot reproduce your results on deepfashion, so I will not compare your method in my paper. Sorry about this.

**Comment by siyuhuang** [comment]
> @siyuhuang I cannot reproduce your results on deepfashion, so I will not compare your method in my paper. Sorry about this.

It's OK. I'm sorry that cannot figure out what's wrong with your case.

**Comment by shyern** [comment]
Have you solved this problem? I have the same problem.

**Comment by shyern** [comment]
I have solved this problem. The DeepFashion dataset should be downloaded from the link of this code. There is some origination difference between this code and PATN about the DeepFashion dataset.

**Comment by siyuhuang** [comment]
> I have solved this problem. The DeepFashion dataset should be downloaded from the link of this code. There is some origination difference between this code and PATN about the DeepFashion dataset.

Thanks @shyern ! 

@linyh1998 @Ha0Tang
