### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by huang1030** [siyuhuang/PoseStylizer#11]
Thanks for your model, when I only have one GPU, which part should I modify so that the program can run. According to the method in question 2, I still have the following error

RuntimeError: Error(s) in loading state_dict for stylegenerator:
Missing key(s) in state_dict: "model.psf_down.1.weight", "model.psf_down.2.weight", "model.psf_down.2.bias", "model.psf_down.2.running_mean", "model.psf_down.2.running_var", "model.bps_down.1.weight", "model.bps_down.2.weight", "model.bps_down.2.bias", "model.bps_down.2.running_mean", "model.bps_down.2.running_var", "model.down_blocks.0.conv_block_down_stream1.0.weight", "model.down_blocks.0.conv_block_down_stream1.1.weight", "model.down_blocks.0.conv_block_down_stream1.1.bias", "model.down_blocks.0.conv_block_down_stream1.1.running_mean", "model.down_blocks.0.conv_block_down_stream1.1.running_var", "model.down_blocks.0.conv_block_stream1.1.weight", "model.down_blocks.0.conv_block_stream1.2.weight", "model.down_blocks.0.conv_block_stream1.2.bias", "model.down_blocks.0.conv_block_stream1.2.running_mean", "model.down_blocks.0.conv_block_stream1.2.running_var", "model.down_blocks.0.conv_block_down_stream2.0.weight", "model.down_blocks.0.conv_block_down_stream2.1.weight", "model.down_blocks.0.conv_block_down_stream2.1.bias", "model.down_blocks.0.conv_block_down_stream2.1.running_mean", "model.down_blocks.0.conv_block_down_stream2.1.running_var", "model.down_blocks.0.conv_block_stream2.1.weight", "model.down_blocks.1.conv_block_down_stream1.0.weight", "model.down_blocks.1.conv_block_down_stream1.1.weight", "model.down_blocks.1.conv_block_down_stream1.1.bias", "model.down_blocks.1.conv_block_down_stream1.1.running_mean", "model.down_blocks.1.conv_block_down_stream1.1.running_var", "model.down_blocks.1.conv_block_stream1.1.weight", "model.down_blocks.1.conv_block_stream1.2.weight", "model.down_blocks.1.conv_block_stream1.2.bias",

**Comment by siyuhuang** [comment]
Could you print out the state_dict to see what happens?

**Comment by wardaddy24** [comment]
I was getting the same error. The error is due to the fact that the model is saved using nn.DataParallel, which stores the model in the module, and now you are trying to load it without DataParallel.
The below link will solve your issue.
https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

**Comment by RanaSMS** [comment]
> I was getting the same error. The error is due to the fact that the model is saved using nn.DataParallel, which stores the model in the module, and now you are trying to load it without DataParallel. The below link will solve your issue. https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

where to save the the state_dict parameters according to the solution :
torch.save(model.module.state_dict(), path_to_file) ???
