### ISSUE TITLE
confusing resulting output

### ISSUE THREAD

**Issue by RanaSMS** [siyuhuang/PoseStylizer#13]
i've run the pose stylizer for the pretrained model and i get this output . is this correct ?? or have i any error?
i want to get the resulting generated image. as in paper

![0188_c2s2_149727_03 jpg___0188_c4s6_008910_07 jpg_vis](https://github.com/siyuhuang/PoseStylizer/assets/44338280/e6ec0090-66d7-4598-9e85-671b1ecdc41e)

**Comment by siyuhuang** [comment]
Could you take a look at these issues to see if they can address your problem?

https://github.com/siyuhuang/PoseStylizer/issues/11
https://github.com/siyuhuang/PoseStylizer/issues/10
https://github.com/siyuhuang/PoseStylizer/issues/7

**Comment by RanaSMS** [comment]
thanks for your response

the error is 
**Not found checkpoints. Network from scratch.**

i've downloaded from your  drive link:https://drive.google.com/drive/folders/1LKFYZvwizRpDxslWoyUePC9XG0cpqLzT

 and put them under the code directory and it doesn't work .
should i put them in certain directory??. i tried different folders but the same error appears

**Comment by siyuhuang** [comment]
Should be structured like `PoseStylizer/checkpoint/fashionAPS`

**Comment by RanaSMS** [comment]
thank you . i create the folder for marketAPS
but the error now is :

**RuntimeError: Error(s) in loading state_dict for stylegenerator**

![image](https://github.com/siyuhuang/PoseStylizer/assets/44338280/4f5440b3-6fc5-4390-a06e-21191a8f9c69)

**Comment by RanaSMS** [comment]
> thank you . i create the folder for marketAPS but the error now is :
> 
> **RuntimeError: Error(s) in loading state_dict for stylegenerator**
> 
> ![image](https://user-images.githubusercontent.com/44338280/266821059-4f5440b3-6fc5-4390-a06e-21191a8f9c69.png)

where the state_dict is saved?
i'm trying  to follow the solution that find an appropriate  state_dict  loading as in :https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/17.

**Comment by RanaSMS** [comment]
i solve the problem by the this approach 

https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/12

thanks so much
