### ISSUE TITLE
error message "no session"

### ISSUE THREAD

**Issue by chikiuso** [siyuhuang/PoseStylizer#2]
Hi, thanks for your great work, I tried running with the pre-trained model but got the error message as follows, could I have some hints? thanks :

no sessions

 "module.model.up_blocks_fg.2.conv1.bias", "module.model.up_blocks_fg.2.patchnorm2.fc.weight", "module.model.up_blocks_fg.2.patchnorm2.fc.bias", "module.model.up_blocks_fg.2.att.weight", "module.model.up_blocks_fg.2.att.bias", "module.model.up_blocks_fg.3.image_up_sample.weight", "module.model.up_blocks_fg.3.image_up_sample.bias", "module.model.up_blocks_fg.3.patchnorm1.fc.weight", "module.model.up_blocks_fg.3.patchnorm1.fc.bias", "module.model.up_blocks_fg.3.conv1.weight", "module.model.up_blocks_fg.3.conv1.bias", "module.model.up_blocks_fg.3.patchnorm2.fc.weight", "module.model.up_blocks_fg.3.patchnorm2.fc.bias", "module.model.up_blocks_fg.3.att.weight", "module.model.up_blocks_fg.3.att.bias", "module.model.up_blocks_fg.4.image_up_sample.weight", "module.model.up_blocks_fg.4.image_up_sample.bias", "module.model.up_blocks_fg.4.patchnorm1.fc.weight", "module.model.up_blocks_fg.4.patchnorm1.fc.bias", "module.model.up_blocks_fg.4.conv1.weight", "module.model.up_blocks_fg.4.conv1.bias", "module.model.up_blocks_fg.4.patchnorm2.fc.weight", "module.model.up_blocks_fg.4.patchnorm2.fc.bias", "module.model.up_blocks_fg.4.att.weight", "module.model.up_blocks_fg.4.att.bias", "module.model.up_blocks_full.0.layer.0.weight", "module.model.up_blocks_full.0.layer.0.bias", "module.model.up_blocks_full.1.layer.0.weight", "module.model.up_blocks_full.1.layer.0.bias", "module.model.up_blocks_full.2.layer.0.weight", "module.model.up_blocks_full.2.layer.0.bias", "module.model.up_blocks_full.3.layer.0.weight", "module.model.up_blocks_full.3.layer.0.bias", "module.model.up_blocks_full.4.layer.1.weight", "module.model.up_blocks_full.4.layer.1.bias", "module.model.out_node_full.1.weight", "module.model.out_node_full.1.bias".

**Comment by siyuhuang** [comment]
Please let **`netG = nn.DataParallel(netG, device_ids=gpu_ids)`** in this [line](https://github.com/siyuhuang/PoseStylizer/blob/4ffbdf48eb1ec6477aeb7c3068b20c52754939a9/models/networks.py#L124) 

As the networks are trained under multi-gpus, the networks are saved under `nn.DataParallel()` in this [line](https://github.com/siyuhuang/PoseStylizer/blob/4ffbdf48eb1ec6477aeb7c3068b20c52754939a9/models/PoseStyleNet.py#L277). The downloaded pretrained network weights should be loaded into networks wrapped with `nn.DataParallel()`.

**Comment by chikiuso** [comment]
Hi @siyuhuang , thanks for your help. Is this project based on coda 9.0? or 10.0?

**Comment by siyuhuang** [comment]
> Hi @siyuhuang , thanks for your help. Is this project based on coda 9.0? or 10.0?

We used cuda 10.0. But we believe cuda version<10 may also work.

**Comment by chikiuso** [comment]
thanks for your help!

**Comment by RanaSMS** [comment]
> Please let **`netG = nn.DataParallel(netG, device_ids=gpu_ids)`** in this [line](https://github.com/siyuhuang/PoseStylizer/blob/4ffbdf48eb1ec6477aeb7c3068b20c52754939a9/models/networks.py#L124)
> 
> As the networks are trained under multi-gpus, the networks are saved under `nn.DataParallel()` in this [line](https://github.com/siyuhuang/PoseStylizer/blob/4ffbdf48eb1ec6477aeb7c3068b20c52754939a9/models/PoseStyleNet.py#L277). The downloaded pretrained network weights should be loaded into networks wrapped with `nn.DataParallel()`.

how can i do that??
