### ISSUE TITLE
Generator block

### ISSUE THREAD

**Issue by Zeros12** [siyuhuang/PoseStylizer#4]
Hi,

Thanks for great work! I have few questions.

In your paper, the architecture (Figure 3) is showing that the target pose map is the input of the generator block. Are you directly injecting the target pose to the generator (decoder) block or the pose map is passing through any convolutional layer first? In the first block of the generator, is the target pose directly passing through the deconvolutional layer without being convoluted?

**Comment by siyuhuang** [comment]
As [here](https://github.com/siyuhuang/PoseStylizer/blob/d1d832781ddfd3efde24bf32b36a4074fafebcc1/models/APS.py#L89), the pose map `bpt` does not go through any conv layer. In the first block, `bpt` is the input. In later blocks, `bpt` is concatenated with the image generation stream `pt`.

**Comment by amena6490** [comment]
Thank you.

**Comment by amena6490** [comment]
Thanks.

**Comment by Zeros12** [comment]
Thanks.
