### ISSUE TITLE
annotation file

### ISSUE THREAD

**Issue by limeverry** [siyuhuang/PoseStylizer#5]
Hello.

Thank you for sharing your wonderful work.

I am working on applying another database to the code, but I am having a hard time not knowing where to create the annotation file.

Is there a way to do that in the code you published? If not, can you please share how?

Thank you

**Comment by siyuhuang** [comment]
Following the Data Preparation section in README, you should prepare 

- **train/test images**
- **keypoint annotations** (`annotation.csv`, the keypoint coordinates )
- **pose transfer pairs**  (`pairs.csv`, names of images of the same person with different poses). 

Please refer to those `.csv` files to see their formats. 

Then, generating the pose heatmaps and start training!

**Comment by deepai-lab** [comment]
Hi, I run tool/compute_coordinates.py to generate annotations file (.csv), but it does not save any annotation file in the output file and I am always getting the following results for all images:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

**Comment by siyuhuang** [comment]
> Hi, I run tool/compute_coordinates.py to generate annotations file (.csv), but it does not save any annotation file in the output file and I am always getting the following results for all images:
> [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

I encountered the same problem before. I remember certain line of codes in `tool/compute_coordinates.py` fails in Python3. I'd recommend to run it in Python2.

**Comment by deepai-lab** [comment]
Thank you. solved.

**Comment by wardaddy24** [comment]
In case you don't have python 2 change it to python 3 it will work.
From python 2:
print >> result_file, "%s: %s: %s" % (image_name, str(list(pose_cords[:, 0])), str(list(pose_cords[:, 1])))
From python 3:
print("%s: %s: %s" % (image_name, str(list(pose_cords[:, 0])), str(list(pose_cords[:, 1]))),file=result_file)
