### ISSUE TITLE
No of blocks in encoder and generator

### ISSUE THREAD

**Issue by deepai-lab** [siyuhuang/PoseStylizer#6]
Hi @siyuhuang,
I am just wondering how to change the number of blocks in the encoder and decoder in your code? For example, if I would like to use 2 blocks in both encoder and decoder, how can I do that? Thanks in advance.

**Comment by siyuhuang** [comment]
`G_n_downsampling` in args is the number of encoder and decoder blocks. Setting `G_n_downsampling = 2` means there are 2 blocks in both encoder and decoder.

**Comment by deepai-lab** [comment]
@siyuhuang Thank you so much for your reply. When I change G_n_downsampling = 2, it works. However, when I change **G_n_downsampling = 1**, I got the following error. Can you please tell me how to solve this problem?

`RuntimeError: Sizes of tensors must match except in dimension 2. Got 128 and 256`

**Comment by siyuhuang** [comment]
> @siyuhuang Thank you so much for your reply. When I change G_n_downsampling = 2, it works. However, when I change **G_n_downsampling = 1**, I got the following error. Can you please tell me how to solve this problem?
> 
> `RuntimeError: Sizes of tensors must match except in dimension 2. Got 128 and 256`

It may not support a `G_n_downsampling=1`
