### ISSUE TITLE
Noises on generated images, how to avoid this problems

### ISSUE THREAD

**Issue by Amazingren** [siyuhuang/PoseStylizer#7]
Hi Siyu, 
Thanks for your impressive work. And I download your code and checkpoints you released in 百度云. However, when I try to generate images based on your checkpoints, I got those images:

I wonder is there any method to solve this?
![image](https://user-images.githubusercontent.com/31409716/99150436-91bb7780-26cf-11eb-9193-80353437d2ec.png)
 
![image](https://user-images.githubusercontent.com/31409716/99150445-9849ef00-26cf-11eb-935f-cec86a0d4153.png)

I am looking forward to your reply. 

Thanks Again!

**Comment by siyuhuang** [comment]
It seems like you don't load the checkpoint correctly. Please kindly check the checkpoint loading process.

**Comment by Amazingren** [comment]
> It seems like you don't load the checkpoint correctly. Please kindly check the checkpoint loading process.

Thanks for your reply. It actually is the problem of checkpoint loading matters. Thanks again!

**Comment by RanaSMS** [comment]
> > It seems like you don't load the checkpoint correctly. Please kindly check the checkpoint loading process.
> 
> Thanks for your reply. It actually is the problem of checkpoint loading matters. Thanks again!

where could i put the checkpoints files???
can i put them under the main code root? or under specific folder?

**Comment by RanaSMS** [comment]
the error is 

---------- Networks initialized -------------
model [TransferModel] was created
testing samples: 100000/2
CustomDatasetDataLoader
dataset [KeyDataset] was created
Loading data pairs ...
Loading data pairs finished ...
PoseStyleNet
initialization method [normal]
**Not found checkpoints. Network from scratch.**
