### ISSUE TITLE
Discriminators

### ISSUE THREAD

**Issue by Zeros12** [siyuhuang/PoseStylizer#8]
Hi,  

You have used two discriminators, one for appearance and the other for pose. I am wondering if I want to use one discriminator only, such as only the appearance discriminator while there will be no pose discriminator, how can I do that in your code?

Thanks in advance.

**Comment by siyuhuang** [comment]
`--with_D_PP`  and  `--with_D_PB` in `.sh` denotes the using of two discriminators.

**Comment by Zeros12** [comment]
Hi, This is the discriminator architecture of Cycle GAN. 

`Layer # Discriminators
```
1 CONV-(N64,K4,S2), LeakyReLU

2 CONV-(N128,K4,S2), InstanceNorm, LeakyReLU

3 CONV-(N256,K4,S2), InstanceNorm, LeakyReLU

4 CONV-(N512,K4,S1), InstanceNorm, LeakyReLU

5 CONV-(N1,K4,S1)`
```

I am just wondering what is the architecture of your discriminator?

**Comment by siyuhuang** [comment]
> Hi, This is the discriminator architecture of Cycle GAN.
> 
> `Layer # Discriminators
> 
> ```
> 1 CONV-(N64,K4,S2), LeakyReLU
> 
> 2 CONV-(N128,K4,S2), InstanceNorm, LeakyReLU
> 
> 3 CONV-(N256,K4,S2), InstanceNorm, LeakyReLU
> 
> 4 CONV-(N512,K4,S1), InstanceNorm, LeakyReLU
> 
> 5 CONV-(N1,K4,S1)`
> ```
> 
> I am just wondering what is the architecture of your discriminator?

See [this](https://github.com/siyuhuang/PoseStylizer/blob/d1d832781ddfd3efde24bf32b36a4074fafebcc1/models/networks.py#L250)

**Comment by Zeros12** [comment]
Thank you so much for your reply.

I have another question. You have two discriminators, appearance and pose discriminators. 

So, I believe the inputs of the appearance discriminator are the source image (Is) and the generated image (Ig), and the inputs of the pose discriminator are the target pose (Pt) and the generated image (Ig). Is that correct? Or are you giving any other images such as the real target image in the discriminators?

**Comment by siyuhuang** [comment]
> Thank you so much for your reply.
> 
> I have another question. You have two discriminators, appearance and pose discriminators.
> 
> So, I believe the inputs of the appearance discriminator are the source image (Is) and the generated image (Ig), and the inputs of the pose discriminator are the target pose (Pt) and the generated image (Ig). Is that correct? Or are you giving any other images such as the real target image in the discriminators?

Please see the codes here https://github.com/siyuhuang/PoseStylizer/blob/d1d832781ddfd3efde24bf32b36a4074fafebcc1/models/PoseStyleNet.py#L181
