### ISSUE TITLE
pre trained models params

### ISSUE THREAD

**Issue by orydatadudes** [siyuhuang/PoseStylizer#9]
when try to bash test_market.sh i am getting the following error
i think its because the bush file params don't fit the training params 

Traceback (most recent call last):
  File "/home/X/projects/PoseStylizer/test.py", line 34, in <module>
    model = create_model(opt)
  File "/home/X/projects/PoseStylizer/models/models.py", line 12, in create_model
    model.initialize(opt)
  File "/home/X/projects/PoseStylizer/models/PoseStyleNet.py", line 53, in initialize
    self.load_network(self.netG, 'netG', which_epoch)
  File "/home/X/projects/PoseStylizer/models/base_model.py", line 66, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/X/anaconda3/envs/posestyle/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for stylegenerator:
	Missing key(s) in state_dict: "model.psf_down.1.weight", "model.psf_down.2.weight", "model.psf_down.2.bias", "model.psf_down.2.running_mean", "model.psf_down.2.running_var", "model.bps_down.1.weight", "model.bps_down.2.weight", "model.bps_down.2.bias", "model.bps_down.2.running_mean", "model.bps_down.2.running_var", "model.down_blocks.0.conv_block_down_stream1.0.weight", "model.down_blocks.0.conv_block_down_stream1.1.weight", "model.down_blocks.0.conv_block_down_stream1.1.bias", "model.down_blocks.0.conv_block_down_stream1.1.running_mean", "model.down_blocks.0.conv_block_down_stream1.1.running_var", "model.down_blocks.0.conv_block_stream1.1.weight", "model.down_blocks.0.conv_block_stream1.2.weight", "model.down_blocks.0.conv_block_stream1.2.bias", "model.down_blocks.0.conv_block_stream1.2.running_mean", "model.down_blocks.0.conv_block_stream1.2.running_var", "model.down_blocks.0.conv_block_down_stream2.0.weight", "model.down_blocks.0.conv_block_down_stream2.1.weight", "model.down_blocks.0.conv_block_down_stream2.1.bias", "model.down_blocks.0.conv_block_down_stream2.1.running_mean", "model.down_blocks.0.conv_block_down_stream2.1.running_var", "model.down_blocks.0.conv_block_stream2.1.weight", "model.down_blocks.1.conv_block_down_stream1.0.weight", "model.down_blocks.1.conv_block_down_stream1.1.weight", "model.down_blocks.1.conv_block_down_stream1.1.bias", "model.down_blocks.1.conv_block_down_stream1.1.running_mean", "model.down_blocks.1.conv_block_down_stream1.1.running_var", "model.down_blocks.1.conv_block_stream1.1.weight", "model.down_blocks.1.conv_block_stream1.2.weight", "model.down_blocks.1.conv_block_stream1.2.bias", "model.down_blocks.1.conv_block_stream1.2.running_mean", "model.down_blocks.1.conv_block_stream1.2.running_var", "model.down_blocks.1.conv_block_down_stream2.0.weight", "model.down_blocks.1.conv_block_down_stream2.1.weight", "model.down_blocks.1.conv_block_down_stream2.1.bias", "model.down_blocks.1.conv_block_down_stream2.1.running_mean", "model.down_blocks.1.conv_block_down_stream2.1.running_var", "model.down_blocks.1.conv_block_stream2.1.weight", "model.down_blocks.2.conv_block_down_stream1.0.weight", "model.down_blocks.2.conv_block_down_stream1.1.weight", "model.down_blocks.2.conv_block_down_stream1.1.bias", "model.down_blocks.2.conv_block_down_stream1.1.running_mean", "model.down_blocks.2.conv_block_down_stream1.1.running_var", "model.down_blocks.2.conv_block_stream1.1.weight", "model.down_blocks.2.conv_block_stream1.2.weight", "model.down_blocks.2.conv_block_stream1.2.bias", "model.down_blocks.2.conv_block_stream1.2.running_mean", "model.down_blocks.2.conv_block_stream1.2.running_var", "model.down_blocks.2.conv_block_down_stream2.0.weight", "model.down_blocks.2.conv_block_down_stream2.1.weight", "model.down_blocks.2.conv_block_down_stream2.1.bias", "model.down_blocks.2.conv_block_down_stream2.1.running_mean", "model.down_blocks.2.conv_block_down_stream2.1.running_var", "model.down_blocks.2.conv_block_stream2.1.weight", "model.down_blocks.3.conv_block_down_stream1.0.weight", "model.down_blocks.3.conv_block_down_stream1.1.weight", "model.down_blocks.3.conv_block_down_stream1.1.bias", "model.down_blocks.3.conv_block_down_stream1.1.running_mean", "model.down_blocks.3.conv_block_down_stream1.1.running_var", "model.down_blocks.3.conv_block_stream1.1.weight", "model.down_blocks.3.conv_block_stream1.2.weight", "model.down_blocks.3.conv_block_stream1.2.bias", "model.down_blocks.3.conv_block_stream1.2.running_mean", "model.down_blocks.3.conv_block_stream1.2.running_var", "model.down_blocks.3.conv_block_down_stream2.0.weight", "model.down_blocks.3.conv_block_down_stream2.1.weight", "model.down_blocks.3.conv_block_down_stream2.1.bias", "model.down_blocks.3.conv_block_down_stream2.1.running_mean", "model.down_blocks.3.conv_block_down_stream2.1.running_var", "model.down_blocks.3.conv_block_stream2.1.weight", "model.up_blocks_fg.0.image_up_sample.weight", "model.up_blocks_fg.0.image_up_sample.bias", "model.up_blocks_fg.0.patchnorm1.fc.weight", "model.up_blocks_fg.0.patchnorm1.fc.bias", "model.up_blocks_fg.0.conv1.weight", "model.up_blocks_fg.0.conv1.bias", "model.up_blocks_fg.0.patchnorm2.fc.weight", "model.up_blocks_fg.0.patchnorm2.fc.bias", "model.up_blocks_fg.0.att.weight", "model.up_blocks_fg.0.att.bias", "model.up_blocks_fg.1.image_up_sample.weight", "model.up_blocks_fg.1.image_up_sample.bias", "model.up_blocks_fg.1.patchnorm1.fc.weight", "model.up_blocks_fg.1.patchnorm1.fc.bias", "model.up_blocks_fg.1.conv1.weight", "model.up_blocks_fg.1.conv1.bias", "model.up_blocks_fg.1.patchnorm2.fc.weight", "model.up_blocks_fg.1.patchnorm2.fc.bias", "model.up_blocks_fg.1.att.weight", "model.up_blocks_fg.1.att.bias", "model.up_blocks_fg.2.image_up_sample.weight", "model.up_blocks_fg.2.image_up_sample.bias", "model.up_blocks_fg.2.patchnorm1.fc.weight", "model.up_blocks_fg.2.patchnorm1.fc.bias", "model.up_blocks_fg.2.conv1.weight", "model.up_blocks_fg.2.conv1.bias", "model.up_blocks_fg.2.patchnorm2.fc.weight", "model.up_blocks_fg.2.patchnorm2.fc.bias", "model.up_blocks_fg.2.att.weight", "model.up_blocks_fg.2.att.bias", "model.up_blocks_fg.3.image_up_sample.weight", "model.up_blocks_fg.3.image_up_sample.bias", "model.up_blocks_fg.3.patchnorm1.fc.weight", "model.up_blocks_fg.3.patchnorm1.fc.bias", "model.up_blocks_fg.3.conv1.weight", "model.up_blocks_fg.3.conv1.bias", "model.up_blocks_fg.3.patchnorm2.fc.weight", "model.up_blocks_fg.3.patchnorm2.fc.bias", "model.up_blocks_fg.3.att.weight", "model.up_blocks_fg.3.att.bias", "model.up_blocks_full.0.layer.0.weight", "model.up_blocks_full.0.layer.0.bias", "model.up_blocks_full.0.layer.1.weight", "model.up_blocks_full.0.layer.1.bias", "model.up_blocks_full.0.layer.1.running_mean", "model.up_blocks_full.0.layer.1.running_var", "model.up_blocks_full.1.layer.0.weight", "model.up_blocks_full.1.layer.0.bias", "model.up_blocks_full.1.layer.1.weight", "model.up_blocks_full.1.layer.1.bias", "model.up_blocks_full.1.layer.1.running_mean", "model.up_blocks_full.1.layer.1.running_var", "model.up_blocks_full.2.layer.0.weight", "model.up_blocks_full.2.layer.0.bias", "model.up_blocks_full.2.layer.1.weight", "model.up_blocks_full.2.layer.1.bias", "model.up_blocks_full.2.layer.1.running_mean", "model.up_blocks_full.2.layer.1.running_var", "model.up_blocks_full.3.layer.1.weight", "model.up_blocks_full.3.layer.1.bias", "model.up_blocks_full.3.layer.2.weight", "model.up_blocks_full.3.layer.2.bias", "model.up_blocks_full.3.layer.2.running_mean", "model.up_blocks_full.3.layer.2.running_var", "model.out_node_full.1.weight", "model.out_node_full.1.bias". 
	Unexpected key(s) in state_dict: "module.model.psf_down.1.weight", "module.model.psf_down.2.weight", "module.model.psf_down.2.bias", "module.model.psf_down.2.running_mean", "module.model.psf_down.2.running_var", "module.model.psf_down.2.num_batches_tracked", "module.model.bps_down.1.weight", "module.model.bps_down.2.weight", "module.model.bps_down.2.bias", "module.model.bps_down.2.running_mean", "module.model.bps_down.2.running_var", "module.model.bps_down.2.num_batches_tracked", "module.model.down_blocks.0.conv_block_down_stream1.0.weight", "module.model.down_blocks.0.conv_block_down_stream1.1.weight", "module.model.down_blocks.0.conv_block_down_stream1.1.bias", "module.model.down_blocks.0.conv_block_down_stream1.1.running_mean", "module.model.down_blocks.0.conv_block_down_stream1.1.running_var", "module.model.down_blocks.0.conv_block_down_stream1.1.num_batches_tracked", "module.model.down_blocks.0.conv_block_stream1.1.weight", "module.model.down_blocks.0.conv_block_stream1.2.weight", "module.model.down_blocks.0.conv_block_stream1.2.bias", "module.model.down_blocks.0.conv_block_stream1.2.running_mean", "module.model.down_blocks.0.conv_block_stream1.2.running_var", "module.model.down_blocks.0.conv_block_stream1.2.num_batches_tracked", "module.model.down_blocks.0.conv_block_down_stream2.0.weight", "module.model.down_blocks.0.conv_block_down_stream2.1.weight", "module.model.down_blocks.0.conv_block_down_stream2.1.bias", "module.model.down_blocks.0.conv_block_down_stream2.1.running_mean", "module.model.down_blocks.0.conv_block_down_stream2.1.running_var", "module.model.down_blocks.0.conv_block_down_stream2.1.num_batches_tracked", "module.model.down_blocks.0.conv_block_stream2.1.weight", "module.model.down_blocks.1.conv_block_down_stream1.0.weight", "module.model.down_blocks.1.conv_block_down_stream1.1.weight", "module.model.down_blocks.1.conv_block_down_stream1.1.bias", "module.model.down_blocks.1.conv_block_down_stream1.1.running_mean", "module.model.down_blocks.1.conv_block_down_stream1.1.running_var", "module.model.down_blocks.1.conv_block_down_stream1.1.num_batches_tracked", "module.model.down_blocks.1.conv_block_stream1.1.weight", "module.model.down_blocks.1.conv_block_stream1.2.weight", "module.model.down_blocks.1.conv_block_stream1.2.bias", "module.model.down_blocks.1.conv_block_stream1.2.running_mean", "module.model.down_blocks.1.conv_block_stream1.2.running_var", "module.model.down_blocks.1.conv_block_stream1.2.num_batches_tracked", "module.model.down_blocks.1.conv_block_down_stream2.0.weight", "module.model.down_blocks.1.conv_block_down_stream2.1.weight", "module.model.down_blocks.1.conv_block_down_stream2.1.bias", "module.model.down_blocks.1.conv_block_down_stream2.1.running_mean", "module.model.down_blocks.1.conv_block_down_stream2.1.running_var", "module.model.down_blocks.1.conv_block_down_stream2.1.num_batches_tracked", "module.model.down_blocks.1.conv_block_stream2.1.weight", "module.model.down_blocks.2.conv_block_down_stream1.0.weight", "module.model.down_blocks.2.conv_block_down_stream1.1.weight", "module.model.down_blocks.2.conv_block_down_stream1.1.bias", "module.model.down_blocks.2.conv_block_down_stream1.1.running_mean", "module.model.down_blocks.2.conv_block_down_stream1.1.running_var", "module.model.down_blocks.2.conv_block_down_stream1.1.num_batches_tracked", "module.model.down_blocks.2.conv_block_stream1.1.weight", "module.model.down_blocks.2.conv_block_stream1.2.weight", "module.model.down_blocks.2.conv_block_stream1.2.bias", "module.model.down_blocks.2.conv_block_stream1.2.running_mean", "module.model.down_blocks.2.conv_block_stream1.2.running_var", "module.model.down_blocks.2.conv_block_stream1.2.num_batches_tracked", "module.model.down_blocks.2.conv_block_down_stream2.0.weight", "module.model.down_blocks.2.conv_block_down_stream2.1.weight", "module.model.down_blocks.2.conv_block_down_stream2.1.bias", "module.model.down_blocks.2.conv_block_down_stream2.1.running_mean", "module.model.down_blocks.2.conv_block_down_stream2.1.running_var", "module.model.down_blocks.2.conv_block_down_stream2.1.num_batches_tracked", "module.model.down_blocks.2.conv_block_stream2.1.weight", "module.model.down_blocks.3.conv_block_down_stream1.0.weight", "module.model.down_blocks.3.conv_block_down_stream1.1.weight", "module.model.down_blocks.3.conv_block_down_stream1.1.bias", "module.model.down_blocks.3.conv_block_down_stream1.1.running_mean", "module.model.down_blocks.3.conv_block_down_stream1.1.running_var", "module.model.down_blocks.3.conv_block_down_stream1.1.num_batches_tracked", "module.model.down_blocks.3.conv_block_stream1.1.weight", "module.model.down_blocks.3.conv_block_stream1.2.weight", "module.model.down_blocks.3.conv_block_stream1.2.bias", "module.model.down_blocks.3.conv_block_stream1.2.running_mean", "module.model.down_blocks.3.conv_block_stream1.2.running_var", "module.model.down_blocks.3.conv_block_stream1.2.num_batches_tracked", "module.model.down_blocks.3.conv_block_down_stream2.0.weight", "module.model.down_blocks.3.conv_block_down_stream2.1.weight", "module.model.down_blocks.3.conv_block_down_stream2.1.bias", "module.model.down_blocks.3.conv_block_down_stream2.1.running_mean", "module.model.down_blocks.3.conv_block_down_stream2.1.running_var", "module.model.down_blocks.3.conv_block_down_stream2.1.num_batches_tracked", "module.model.down_blocks.3.conv_block_stream2.1.weight", "module.model.up_blocks_fg.0.image_up_sample.weight", "module.model.up_blocks_fg.0.image_up_sample.bias", "module.model.up_blocks_fg.0.patchnorm1.fc.weight", "module.model.up_blocks_fg.0.patchnorm1.fc.bias", "module.model.up_blocks_fg.0.conv1.weight", "module.model.up_blocks_fg.0.conv1.bias", "module.model.up_blocks_fg.0.patchnorm2.fc.weight", "module.model.up_blocks_fg.0.patchnorm2.fc.bias", "module.model.up_blocks_fg.0.att.weight", "module.model.up_blocks_fg.0.att.bias", "module.model.up_blocks_fg.1.image_up_sample.weight", "module.model.up_blocks_fg.1.image_up_sample.bias", "module.model.up_blocks_fg.1.patchnorm1.fc.weight", "module.model.up_blocks_fg.1.patchnorm1.fc.bias", "module.model.up_blocks_fg.1.conv1.weight", "module.model.up_blocks_fg.1.conv1.bias", "module.model.up_blocks_fg.1.patchnorm2.fc.weight", "module.model.up_blocks_fg.1.patchnorm2.fc.bias", "module.model.up_blocks_fg.1.att.weight", "module.model.up_blocks_fg.1.att.bias", "module.model.up_blocks_fg.2.image_up_sample.weight", "module.model.up_blocks_fg.2.image_up_sample.bias", "module.model.up_blocks_fg.2.patchnorm1.fc.weight", "module.model.up_blocks_fg.2.patchnorm1.fc.bias", "module.model.up_blocks_fg.2.conv1.weight", "module.model.up_blocks_fg.2.conv1.bias", "module.model.up_blocks_fg.2.patchnorm2.fc.weight", "module.model.up_blocks_fg.2.patchnorm2.fc.bias", "module.model.up_blocks_fg.2.att.weight", "module.model.up_blocks_fg.2.att.bias", "module.model.up_blocks_fg.3.image_up_sample.weight", "module.model.up_blocks_fg.3.image_up_sample.bias", "module.model.up_blocks_fg.3.patchnorm1.fc.weight", "module.model.up_blocks_fg.3.patchnorm1.fc.bias", "module.model.up_blocks_fg.3.conv1.weight", "module.model.up_blocks_fg.3.conv1.bias", "module.model.up_blocks_fg.3.patchnorm2.fc.weight", "module.model.up_blocks_fg.3.patchnorm2.fc.bias", "module.model.up_blocks_fg.3.att.weight", "module.model.up_blocks_fg.3.att.bias", "module.model.up_blocks_full.0.layer.0.weight", "module.model.up_blocks_full.0.layer.0.bias", "module.model.up_blocks_full.0.layer.1.weight", "module.model.up_blocks_full.0.layer.1.bias", "module.model.up_blocks_full.0.layer.1.running_mean", "module.model.up_blocks_full.0.layer.1.running_var", "module.model.up_blocks_full.0.layer.1.num_batches_tracked", "module.model.up_blocks_full.1.layer.0.weight", "module.model.up_blocks_full.1.layer.0.bias", "module.model.up_blocks_full.1.layer.1.weight", "module.model.up_blocks_full.1.layer.1.bias", "module.model.up_blocks_full.1.layer.1.running_mean", "module.model.up_blocks_full.1.layer.1.running_var", "module.model.up_blocks_full.1.layer.1.num_batches_tracked", "module.model.up_blocks_full.2.layer.0.weight", "module.model.up_blocks_full.2.layer.0.bias", "module.model.up_blocks_full.2.layer.1.weight", "module.model.up_blocks_full.2.layer.1.bias", "module.model.up_blocks_full.2.layer.1.running_mean", "module.model.up_blocks_full.2.layer.1.running_var", "module.model.up_blocks_full.2.layer.1.num_batches_tracked", "module.model.up_blocks_full.3.layer.1.weight", "module.model.up_blocks_full.3.layer.1.bias", "module.model.up_blocks_full.3.layer.2.weight", "module.model.up_blocks_full.3.layer.2.bias", "module.model.up_blocks_full.3.layer.2.running_mean", "module.model.up_blocks_full.3.layer.2.running_var", "module.model.up_blocks_full.3.layer.2.num_batches_tracked", "module.model.out_node_full.1.weight", "module.model.out_node_full.1.bias".

**Comment by siyuhuang** [comment]
Please see #2 

The pretrained weights should be loaded into networks wrapped with `nn.DataParallel()`.
